[build]
  command = "yarn build"
  publish = "dist"
  
[dev]
  command = "yarn dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = false

[functions]
  directory = "functions/"

[[plugins]]
  package = "netlify-plugin-no-more-404"

  [plugins.inputs]
  
  # change this key to a new one any time you need to restart from scratch
  cacheKey = "12_22_2021-cacheKey"